### ISSUE TITLE
Create a Reminder System

### ISSUE THREAD

**Issue by dineshchhantyal** [dineshchhantyal/cheerpal_frontend#3]
# Create a Reminder System

## Features

- User reminder event creation
- Product recommendation based on events
- Data storage from Amazon and Walmart via web scraping
- Implementation of machine learning techniques

## Task Breakdown

- [ ] #4
  - [ ] Design the reminder form
  - [ ] User location free API if available 
  - [ ] Implement input validation
  - [ ] Store reminder data in the database

- [ ] **Reminder Tracking in Dashboard**
  - [ ] Get user reminders
  - [ ] Show reminders
  - [ ] User proper metrics

- [ ] **Product Recommendation Based on Events**
  - [ ] Analyze event types and associated products
  - [ ] Develop recommendation algorithm
  - [ ] Integrate recommendation system with user reminders

- [ ] **Data Storage from Amazon and Walmart via Web Scraping**
  - [ ] Set up web scraping for Amazon
  - [ ] Set up web scraping for Walmart
  - [ ] Store scraped data in the database

- [ ] **Implementation of Machine Learning Techniques**
  - [ ] Train model using event data and past purchases
  - [ ] Validate and optimize the model
  - [ ] Deploy machine learning model to production
